import requests

url = "http://127.0.0.1:8000/rank-candidates"

payload = {
  "job_title": "Python Machine Learning Engineer",
  "job_description": "We are hiring a Python Machine Learning Engineer with at least 2 years of experience. Strong knowledge of Python, Machine Learning, SQL, and experience building ML models, scoring engines, APIs, or recommendation systems is required.",
  "candidates": [
    {"id":"C1","skills":["Python","Machine Learning","SQL"],"experience_years":2,"projects":["ML Scoring Engine","Recommendation System"]},
    {"id":"C2","skills":["Python","Data Analysis","Pandas"],"experience_years":1,"projects":["Sales Dashboard"]},
    {"id":"C3","skills":["Java","Spring Boot"],"experience_years":3,"projects":["Payment API"]},
    {"id":"C4","skills":["Python","FastAPI","SQL"],"experience_years":2,"projects":["Backend API","Auth Service"]},
    {"id":"C5","skills":["Python","Machine Learning"],"experience_years":4,"projects":["Fraud Detection","Risk Model"]},
    {"id":"C6","skills":["SQL","Tableau"],"experience_years":3,"projects":["BI Dashboard"]},
    {"id":"C7","skills":["Python"],"experience_years":1},
    {"id":"C8","skills":["Python","ML","NLP"],"experience_years":2,"projects":["Resume Parser","Chatbot"]},
    {"id":"C9","skills":["JavaScript","React"],"experience_years":2,"projects":["Frontend Dashboard"]},
    {"id":"C10","skills":["Python","SQL","ML"],"experience_years":3,"projects":["Candidate Ranking Engine"]},

    {"id":"C11","skills":["Python","FastAPI"],"experience_years":2,"projects":["Microservice API"]},
    {"id":"C12","skills":["Python","Statistics"],"experience_years":1,"projects":["Hypothesis Testing"]},
    {"id":"C13","skills":["Java","Hibernate"],"experience_years":4},
    {"id":"C14","skills":["Python","Machine Learning","TensorFlow"],"experience_years":3,"projects":["Image Classifier"]},
    {"id":"C15","skills":["SQL","Power BI"],"experience_years":2},
    {"id":"C16","skills":["Python","Flask"],"experience_years":1,"projects":["REST API"]},
    {"id":"C17","skills":["Python","ML","SQL"],"experience_years":2,"projects":["ML Pipeline","ETL System"]},
    {"id":"C18","skills":["C++","DSA"],"experience_years":3},
    {"id":"C19","skills":["Python","FastAPI","ML"],"experience_years":4,"projects":["Scoring Engine"]},
    {"id":"C20","skills":["Python","Data Science"],"experience_years":2},

    {"id":"C21","skills":["Python","ML"],"experience_years":5,"projects":["AI Hiring Tool"]},
    {"id":"C22","skills":["Python","SQL"],"experience_years":1},
    {"id":"C23","skills":["Python","Machine Learning"],"experience_years":2,"projects":["Spam Classifier"]},
    {"id":"C24","skills":["Python","FastAPI","Docker"],"experience_years":3},
    {"id":"C25","skills":["Data Analysis","Excel"],"experience_years":2},
    {"id":"C26","skills":["Python","ML","NLP"],"experience_years":1},
    {"id":"C27","skills":["Python","SQL","ETL"],"experience_years":4,"projects":["Data Pipeline"]},
    {"id":"C28","skills":["Java","Spring"],"experience_years":2},
    {"id":"C29","skills":["Python","ML"],"experience_years":3,"projects":["Risk Prediction"]},
    {"id":"C30","skills":["Python","Statistics","SQL"],"experience_years":2},

    {"id":"C31","skills":["Python","Machine Learning"],"experience_years":2},
    {"id":"C32","skills":["Python","Flask","SQL"],"experience_years":3},
    {"id":"C33","skills":["Python"],"experience_years":1},
    {"id":"C34","skills":["Python","ML","Deep Learning"],"experience_years":5,"projects":["Vision Model"]},
    {"id":"C35","skills":["SQL","Reporting"],"experience_years":2},
    {"id":"C36","skills":["Python","FastAPI","ML"],"experience_years":2},
    {"id":"C37","skills":["Python","ML"],"experience_years":3,"projects":["Recommendation Engine"]},
    {"id":"C38","skills":["JavaScript","Node.js"],"experience_years":2},
    {"id":"C39","skills":["Python","Data Analysis"],"experience_years":1},
    {"id":"C40","skills":["Python","ML","SQL"],"experience_years":4},

    {"id":"C41","skills":["Python","FastAPI"],"experience_years":2},
    {"id":"C42","skills":["Python","Machine Learning"],"experience_years":3},
    {"id":"C43","skills":["Python","SQL"],"experience_years":1},
    {"id":"C44","skills":["Python","ML","AI"],"experience_years":5,"projects":["AI Matching System"]},
    {"id":"C45","skills":["SQL","Tableau"],"experience_years":3},
    {"id":"C46","skills":["Python","FastAPI","ML"],"experience_years":2},
    {"id":"C47","skills":["Python","ML"],"experience_years":1},
    {"id":"C48","skills":["Python","Machine Learning","SQL"],"experience_years":2,"projects":["Scoring Engine"]},
    {"id":"C49","skills":["Java"],"experience_years":4},
    {"id":"C50","skills":["Python","ML","SQL"],"experience_years":3},

    {"id":"C51","skills":["Python","ML"],"experience_years":2},
    {"id":"C52","skills":["Python","FastAPI"],"experience_years":1},
    {"id":"C53","skills":["Python","SQL"],"experience_years":3},
    {"id":"C54","skills":["Python","Machine Learning"],"experience_years":4},
    {"id":"C55","skills":["Python"],"experience_years":1},
    {"id":"C56","skills":["Python","ML"],"experience_years":2},
    {"id":"C57","skills":["Python","FastAPI","SQL"],"experience_years":3},
    {"id":"C58","skills":["SQL","Power BI"],"experience_years":2},
    {"id":"C59","skills":["Python","Data Analysis"],"experience_years":1},
    {"id":"C60","skills":["Python","ML","SQL"],"experience_years":4},

    {"id":"C61","skills":["Python","ML"],"experience_years":2},
    {"id":"C62","skills":["Python","FastAPI"],"experience_years":3},
    {"id":"C63","skills":["Python","SQL"],"experience_years":1},
    {"id":"C64","skills":["Python","Machine Learning"],"experience_years":5},
    {"id":"C65","skills":["Python"],"experience_years":1},
    {"id":"C66","skills":["Python","ML"],"experience_years":3},
    {"id":"C67","skills":["Python","FastAPI","ML"],"experience_years":2},
    {"id":"C68","skills":["SQL","Reporting"],"experience_years":2},
    {"id":"C69","skills":["Python","Data Science"],"experience_years":1},
    {"id":"C70","skills":["Python","ML","SQL"],"experience_years":4},

    {"id":"C71","skills":["Python","ML"],"experience_years":2},
    {"id":"C72","skills":["Python","FastAPI"],"experience_years":1},
    {"id":"C73","skills":["Python","SQL"],"experience_years":3},
    {"id":"C74","skills":["Python","Machine Learning"],"experience_years":4},
    {"id":"C75","skills":["Python"],"experience_years":1},
    {"id":"C76","skills":["Python","ML"],"experience_years":2},
    {"id":"C77","skills":["Python","FastAPI","SQL"],"experience_years":3},
    {"id":"C78","skills":["SQL","Tableau"],"experience_years":2},
    {"id":"C79","skills":["Python","Data Analysis"],"experience_years":1},
    {"id":"C80","skills":["Python","ML","SQL"],"experience_years":4},

    {"id":"C81","skills":["Python","ML"],"experience_years":2},
    {"id":"C82","skills":["Python","FastAPI"],"experience_years":3},
    {"id":"C83","skills":["Python","SQL"],"experience_years":1},
    {"id":"C84","skills":["Python","Machine Learning"],"experience_years":5},
    {"id":"C85","skills":["Python"],"experience_years":1},
    {"id":"C86","skills":["Python","ML"],"experience_years":3},
    {"id":"C87","skills":["Python","FastAPI","ML"],"experience_years":2},
    {"id":"C88","skills":["SQL","Reporting"],"experience_years":2},
    {"id":"C89","skills":["Python","Data Science"],"experience_years":1},
    {"id":"C90","skills":["Python","ML","SQL"],"experience_years":4},

    {"id":"C91","skills":["Python","ML"],"experience_years":2},
    {"id":"C92","skills":["Python","FastAPI"],"experience_years":1},
    {"id":"C93","skills":["Python","SQL"],"experience_years":3},
    {"id":"C94","skills":["Python","Machine Learning"],"experience_years":4},
    {"id":"C95","skills":["Python"],"experience_years":1},
    {"id":"C96","skills":["Python","ML"],"experience_years":2},
    {"id":"C97","skills":["Python","FastAPI","SQL"],"experience_years":3},
    {"id":"C98","skills":["SQL","Tableau"],"experience_years":2},
    {"id":"C99","skills":["Python","Data Analysis"],"experience_years":1},
    {"id":"C100","skills":["Python","ML","SQL"],"experience_years":4}
  ]
}


response = requests.post(url, json=payload)
print(response.json())
